/**
 * Build src/openings-data.ts from the lichess-org/chess-openings TSV files (CC0).
 *
 *   curl -O https://raw.githubusercontent.com/lichess-org/chess-openings/master/{a,b,c,d,e}.tsv
 *   npx tsx scripts/build-openings.ts path/to/tsv-dir
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { Position } from '../src/position.js';

const dir = process.argv[2];
if (!dir) throw new Error('usage: build-openings.ts <dir with a.tsv..e.tsv>');

const byHash = new Map<string, { eco: string; name: string; plies: number }>();
for (const f of ['a', 'b', 'c', 'd', 'e']) {
  const lines = readFileSync(join(dir, `${f}.tsv`), 'utf8').split('\n').slice(1);
  for (const line of lines) {
    if (!line.trim()) continue;
    const [eco, name, pgn] = line.split('\t');
    const pos = Position.start();
    let plies = 0;
    for (const tok of pgn.split(/\s+/)) {
      if (!tok || /^\d+\.+$/.test(tok)) continue;
      pos.playSan(tok);
      plies++;
    }
    const key = pos.hashHex();
    const prev = byHash.get(key);
    if (!prev || plies < prev.plies) byHash.set(key, { eco, name, plies });
  }
}
const entries = [...byHash.entries()].sort((a, b) => (a[1].eco + a[1].name).localeCompare(b[1].eco + b[1].name));
const body = entries.map(([h, e]) => `${e.eco}\t${e.name}\t${h}`).join('\n');
writeFileSync(
  new URL('../src/openings-data.ts', import.meta.url),
  `// Generated by scripts/build-openings.ts from lichess-org/chess-openings (CC0). Do not edit.\n` +
    `// Format: one opening per line: ECO<TAB>name<TAB>polyglot hash (hex) of the final position.\n` +
    `export const OPENINGS_TSV = ${JSON.stringify(body)};\n`,
);
console.log(`wrote ${entries.length} openings`);
