import { parsePgn, parseGame, writePgn, Position, Game, formatMainline, extractMovetext } from './lib.ts';
const show = (l: string, pgn: string) => { try { const gs = parsePgn(pgn); console.log('==', l, gs.length); for (const g of gs) { console.log(JSON.stringify([...g.headers].filter(([k])=>!['Event','Site','Date','Round','White','Black'].includes(k))), g.errors.length ? g.errors : ''); const w = writePgn(g, {headers:false}); console.log('  ', w.trim().replace(/\n/g,' / ')); const g2 = parseGame(writePgn(g)); const w2 = writePgn(g2, {headers:false}); if (w2 !== w) console.log('  !! rewrite differs:', w2.trim()); } } catch (e) { console.log('THROW', l, (e as Error).stack); } };
show('proto', '1. e4 constructor e5 toString 2. Nf3 *');
show('result ?', '[Result "?"]\n\n1. e4 e5');
show('result weird', '[Result "1-0 (time)"]\n\n1. e4 e5');
show('glyph attached', '1. e4± e5 2. Nf3 *');
show('glyph standalone', '1. e4 ± e5 += 2. Nf3 N *');
show('e8(Q)', '[SetUp "1"]\n[FEN "8/4P3/8/8/8/8/8/k6K w - - 0 1"]\n\n1. e8(Q) *');
show('result in var', '1. e4 (1. d4 1-0) e5 *');
show('var start comment + number', '1. e4 e5 2. Nf3 ({c} 2. Bc4 Nf6) 2... Nc6 *');
show('two games no tags', '1. e4 e5 1-0\n1. d4 d5 0-1\n');
show('no blank line', '[Event "x"]\n1. e4 *\n[Event "y"]\n1. d4 *');
show('missing result then tags', '[Event "x"]\n\n1. e4\n\n[Event "y"]\n\n1. d4 *');
show('comment between siblings', '1. e4 (1. d4) {between} (1. c4) e5 *');
show('tag bs end', '[White "abc\\\\"]\n[Black "x"]\n\n1. e4 *');
show('tag unescaped bs end', '[White "abc\\"]\n[Black "x"]\n\n1. e4 *');
show('percent mid', '1. e4 %notescape e5 *');
show('nag after var', '1. e4 (1. d4) $1 e5 *');
show('nag in var start', '1. e4 e5 ($2 1... c5) *');
show('startcomment empty var', '1. e4 ({only comment}) e5 *');
show('0-0 vs result', '[SetUp "1"]\n[FEN "r3k2r/8/8/8/8/8/8/R3K2R w KQkq - 0 1"]\n\n1. 0-0 0-0-0 0-1');
show('Z0 in check', '[SetUp "1"]\n[FEN "4k3/8/8/8/8/8/8/R3K2r w - - 0 1"]\n\n1. Z0 Kd7 *');
show('ep annotation', '[SetUp "1"]\n[FEN "4k3/8/8/2pP4/8/8/8/4K3 w - c6 0 2"]\n\n2. dxc6 e.p. Kd8 *');
show('black start + comment', '[SetUp "1"]\n[FEN "4k3/8/8/8/8/8/8/4K2R b K - 0 30"]\n\n{start} 30... Kd7 31. O-O *');
show('suffix !+', '1. e4 e5 2. Qh5 Nc6 3. Bc4 Nf6 4. Qxf7#! *');
show('suffix +!', '1. e4 e5 2. Qh5 Nc6 3. Bc4 Nf6 4. Qxf7!# *');
show('multi-line tag val', '[Event "a\nb"]\n\n1. e4 *');
const p = Position.start(); const m = p.parseSan('e4'); formatMainline(p, [m], '*'); console.log('formatMainline mutates start:', p.fen());
console.log(JSON.stringify(extractMovetext('[A "x]y"]\n[B "q\\"]"]\n\n1. e4 *')));
